config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  root 'static#index'
  get 'about' => 'static#about'

  devise_for :users, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'connect'
  }

  get   'connections/start'
  get 'connections/soundcloud'
  match 'connections/soundcloud_auth', to: 'connections#soundcloud_token', via: [:get, :post]
  get   'connections/mixcloud'
  get   'connections/vk'

  get 'collections/soundcloud'
  get 'collections/mixcloud'
  get 'collections/vk'

  get 'player' => 'player#index'
  get 'player/folders'
  get 'player/tracks'
  match 'player/queue', to: 'player#queue', via: [:get, :post]

  get 'dashboard' => 'dashboard#index'
  namespace :dashboard do

    resources :users

    authenticate :user, lambda {|u| u.admin? } do
    end

  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  #rescue_from VkontakteApi::Error, with: :ignore_error
  before_action :authenticate_user!

  def soundcloud

    @user = current_user

    if @user.soundcloud_id?

      FirstSyncSoundcloudJob.perform_later @user
      @user.sync_sc = true
      @user.save

      render template: 'collections/index'

    else

      redirect_to connections_start_path

    end

  end

  def mixcloud

    @user = current_user

    if @user.mixcloud_id?

      FirstSyncMixcloudJob.perform_later @user
      @user.sync_mc = true
      @user.save

      render template: 'collections/index'

    else

      redirect_to connections_start_path

    end

  end

  def vk
    @user = current_user

    if @user.vk_id?

      FirstSyncVkJob.perform_now @user
      @user.sync_vk = true
      @user.save

      render template: 'collections/index'

    else

      redirect_to connections_start_path

    end

  end

  private

  def ignore_error
    puts '======================================='
    puts 'ooops, error! :)'
    puts '======================================='
  end

end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/index.html.erb
<div class="container get-start">
  <div class="row">
    <div class="col s12 m12 l12">
      <h5>Good job!</h5>
      <p>Sync in progress. You can synchronize another service or just go to your collection.</p>
    </div>

    <div class="col s12 m3 l3 service">
      <div class="card soundcloud">
        <div class="card-content white-text">
          <span class="card-title">Soundcloud</span>
          <p>
            <% if @user.sync_sc? %>
                <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw service_sync"></i>
            <% else %>
                <%= image_tag '/images/social/soundcloud.png' %>
            <% end %>
          </p>
        </div>
        <div class="card-action">
          <% if @user.sync_sc? %>
              <span class="btn disabled">in progress</span>
          <% else %>
              <%= link_to 'Sync', connections_soundcloud_path, class: 'btn' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col s12 m3 l3 service">
      <div class="card mixcloud">
        <div class="card-content white-text">
          <span class="card-title">Mixcloud</span>
          <p>
            <% if @user.sync_mc? %>
                <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw service_sync"></i>
            <% else %>
                <%= image_tag '/images/social/mixcloud.png' %>
            <% end %>
          </p>
        </div>
        <div class="card-action">
          <% if @user.sync_mc? %>
              <span class="btn disabled">in progress</span>
          <% else %>
              <%= link_to 'Sync', connections_mixcloud_path, class: 'btn' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col s12 m3 l3 service">
      <div class="card vk">
        <div class="card-content white-text">
          <span class="card-title">Vk</span>
          <p>
            <% if @user.sync_vk? %>
                <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw service_sync"></i>
            <% else %>
                <%= image_tag '/images/social/vkontakte.png' %>
            <% end %>
          </p>
        </div>
        <div class="card-action">
          <% if @user.sync_vk? %>
              <span class="btn disabled">in progress</span>
          <% else %>
              <%= link_to 'Sync', connections_vk_path, class: 'btn' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col s12 m3 l3 service">
      <div class="card mcloud">
        <div class="card-content white-text">
          <span class="card-title">Your collection</span>
          <p>
            <%= image_tag '/images/logo.png' %>
          </p>
        </div>
        <div class="card-action">
          <%= link_to 'Explore', player_path, class: 'btn' %>
        </div>
      </div>
    </div>

  </div>
</div>