config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  root 'static#index'
  get 'about' => 'static#about'

  devise_for :users, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'connect'
  }

  get   'connections/start'
  get 'connections/soundcloud'
  match 'connections/soundcloud_auth', to: 'connections#soundcloud_token', via: [:get, :post]
  get   'connections/mixcloud'
  get   'connections/vk'

  get 'collections/soundcloud'
  get 'collections/mixcloud'
  get 'collections/vk'

  get 'player' => 'player#index'
  get 'player/folders'
  get 'player/tracks'
  match 'player/queue', to: 'player#queue', via: [:get, :post]

  get 'dashboard' => 'dashboard#index'
  namespace :dashboard do

    resources :users

    authenticate :user, lambda {|u| u.admin? } do
    end

  end

end

app/views/shared/_footer.erb
<footer class="page-footer purple-mcloud">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">mCloud.live</h5>
        <p class="grey-text text-lighten-4">mCloud.live - Your music collection</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><%= link_to 'About', about_path, class: 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'Give Feedback', '#ur', class: 'grey-text text-lighten-3 ur' %></li>
            <%=
              if user_signed_in?
                link_to 'logout', destroy_user_session_path, method: 'delete', class: 'grey-text text-lighten-3'
              else
                link_to 'Login', new_user_session_path, class: 'grey-text text-lighten-3'
              end
            %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2016 mCloud.live
      <a class="grey-text text-lighten-4 right" href="http://ampersand.pro" target="_blank">(&) ampersand production</a>
    </div>
  </div>
</footer>
<%= render partial: 'shared/ur' %>
<%= render partial: 'shared/metrika' %>

app/views/shared/_head.html.erb
<head>
  <title>mCloud.live - Your music collection</title>
  <%= stylesheet_link_tag    'https://use.fontawesome.com/2afe48b318.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" href="/favicon/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/favicon/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/favicon/manifest.json">
  <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#3e3287">
  <link rel="shortcut icon" href="/favicon/favicon.ico">
  <meta name="msapplication-config" content="/favicon/browserconfig.xml">
  <meta name="theme-color" content="#ffffff">

  <!-- Facebook -->
  <meta property="og:url"           content="http://mcloud.live" />
	<meta property="og:type"          content="website" />
	<meta property="og:title"         content="mCloud.live" />
	<meta property="og:description"   content="Your music collection" />
	<meta property="og:image"         content="/images/social-cover.png" />

  <!-- Twitter -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@mCloudLive">
  <meta name="twitter:title" content="mCloud.live">
  <meta name="twitter:description" content="Your music collection">
  <meta name="twitter:creator" content="@creator_username">
  <meta name="twitter:image:src" content="/images/social-cover.png">
  <meta name="twitter:domain" content="mcloud.live">

  <!-- Vk and global -->
  <meta name="title" content="mCloud.live - Your music collection" />
  <meta name="description" content="" />
  <link rel="image_src" href="/images/social-cover.png" />

</head>

app/views/shared/_header.erb
<header>
  <nav class="purple-mcloud">
    <div class="container">
      <div class="row">
        <div class="col l12 s12">
          <div class="nav-wrapper">
            <%= link_to 'mCloud.live', root_path, class: 'brand-logo' %>
            <ul id="nav-mobile" class="right">
              <li><%= link_to ('<span class="fa fa-info">').html_safe, about_path %></li>
              <li><%= link_to ('<span class="fa fa-comments-o"></span>').html_safe, '#ur', class: 'ur' %></li>
              <li>
                <%=
                  if user_signed_in?
                    link_to ('<span class="fa fa-sign-out">').html_safe, destroy_user_session_path, method: 'delete'
                  else
                    link_to ('<span class="fa fa-sign-in">').html_safe, new_user_session_path
                  end
                %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_metrika.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
  (function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
      try {
        w.yaCounter39438370 = new Ya.Metrika({
          id:39438370,
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true,
          webvisor:true
        });
      } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = "https://mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
      d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/39438370" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/shared/_notices.html.erb
<div class="flash-message">
  <% flash.each do |name, msg| -%>
      <div class="card-panel system-message <%= name %>">
        <span class="white-text"><%= msg %></span>
        <i class="fa fa-times white-text close-this"></i>
      </div>
  <% end -%>
</div>

app/views/shared/_ur.erb
<!-- Modal Structure -->
<div id="ur" class="modal modal-fixed-footer">
  <div class="modal-content" id="ur-container">
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ur-close">Close</a>
  </div>
</div>